data_space:
  participant_id: test-participant
  assigner_id: provider1
catalog:
  title: Ceit catalog
  keywords:
    - data spaces
    - machine learning
  access_services:
    - http://localhost:9080
  descriptions:
    - This is a sample catalog for Ceit Connector
servers:
  dsp:
    http:
      port: 9080
  gateway:
    http:
      port: 9081
