data_space:
  participant_id: test-participant  # e.g. Connector ID
  assigner_id: provider1  # Data space specific ID for agreements
  assignee_id: consumer1
catalog:
  title: Ceit catalog
  keywords:
    - data spaces
    - machine learning
  access_services:
    - http://localhost:9080
  descriptions:
    - This is a sample catalog for Ceit Connector
servers:
  dsp:
    http:
      port: 8080
  gateway:
    http:
      port: 8081
  exchanger:
    http:
      port: 8082
databases:
  - name: postgresql
    hostname: localhost
    port: 5432
    database: test_db
    username: test
    password: test
